### ISSUE TITLE
Victron SmartShunt has extra MQTT data info

### ISSUE THREAD

**Issue by RoySalisbury** [fl4p/batmon-ha#112]
There is extra info populated in the MQTT data for the Victron Shunt.  Seems to be leftover data from a BMS in the code.

<img width="330" alt="Screenshot 2023-06-06 at 6 00 22 PM" src="https://github.com/fl4p/batmon-ha/assets/12501943/d7bb93ff-21d7-4dd2-8a0f-f75545ebd0dc">

**Comment by fl4p** [comment]
I left this intentionally there, because you can use the aux voltage input to monitor a 2s battery. Not yet implemented though. 
I'll make these fields hide with the next update

**Comment by fl4p** [comment]
fixed with https://github.com/fl4p/batmon-ha/commit/4ddc3348ead1c95a912f9b2c6c8e03a77ec7e07a
