### ISSUE TITLE
Add support for ANT BMS

### ISSUE THREAD

**Issue by fl4p** [fl4p/batmon-ha#13]

**Comment by klbsss** [comment]
Hello! 
I will be grateful for support 
[https://github.com/syssi/esphome-ant-bms](https://github.com/syssi/esphome-ant-bms)

**Comment by Blockvolt** [comment]
Hi, 

if i donate 50$, you can make ANT-BMS working properly? :)

**Comment by fl4p** [comment]
Added ANT Bms with https://github.com/fl4p/batmon-ha/commit/07605b354f2fd4c16cd9b4410989f1b338907d8c

Please open new issues if you encounter problems with this BMS.
