### ISSUE TITLE
Batmon 0.0.6.9 Supervolt integration / Cell- and Battery Voltage is lo less

### ISSUE THREAD

**Issue by Karatzie** [fl4p/batmon-ha#139]
Hi Fabian, 

I tried your last batmon version 0.0.6.9 with my both Supervolt batteries.
The Cell voltage is 0.003322 V instead of 3.322 V.
The battery voltage is 0.013 V instead of 13.0 V.

BR
Andreas

**Comment by fl4p** [comment]
Hi Andreas, please try v70

**Comment by Karatzie** [comment]
Hi Fabian,
the voltage measurements are now ok.
Thank you for your support.

BR
Andreas
