### ISSUE TITLE
Error message during update from 0.0.70 to 0.0.71

### ISSUE THREAD

**Issue by Karatzie** [fl4p/batmon-ha#152]
Hi Fabian.

I got this error message during update from 0.0.70 to 0.0.71.

**The command '/bin/ash -o pipefail -c pip3 install -r requirements.txt' returned a non-zero code: 1**

The update is not performed.

BR
Andreas

**Comment by fl4p** [comment]
duplicate of https://github.com/fl4p/batmon-ha/issues/147

**Comment by Karatzie** [comment]
I use the RP3 and Home Assistant OS 10.5 64 bit.
