### ISSUE TITLE
DALY BMS out of range values

### ISSUE THREAD

**Issue by danbi** [fl4p/batmon-ha#158]
Since October 20 2023 I notice that the recording of my DALY BMS shows extreme values. Like SOC -2330%.  Sometimes it is +3200%.. maybe some calculation goes wrong?

Unfortunately, I cannot catch this in the logs.

**Comment by fl4p** [comment]
thats odd
can you take screenshot of the soc history graph with the outliers and post it here?

**Comment by danbi** [comment]
Here is a snapshot I took when submitting the issue
<img width="580" alt="Screenshot 2023-11-04 at 12 22 36" src="https://github.com/fl4p/batmon-ha/assets/6226266/cd55a110-9ef3-4d73-a432-4294c9f00e8d">

Here is another snapshot I took today, for one of the other packs. It apparently had communication issues during the "no data" period.

<img width="1404" alt="Screenshot 2023-11-07 at 15 08 56" src="https://github.com/fl4p/batmon-ha/assets/6226266/31920c10-8c6b-4e42-8955-26bf6200266f">

Here is the data for all three batteries, from the beginning of the month, together. 
<img width="1407" alt="Screenshot 2023-11-07 at 15 11 38" src="https://github.com/fl4p/batmon-ha/assets/6226266/3cba9476-690a-4e62-a71b-e24a6df3f3ab">

For some reason  I do not see these out of range values anymore, but they are recorded..

**Comment by fl4p** [comment]
Thanks, just noticed that the code for daly bms doesnt verify a checksum. If it did, it would drop these invalid packets. I'll see what I can do

**Comment by danbi** [comment]
This might be the issue. I have generally poor bluetooth connectivity at times to the BMSes, and this might be the cause. The bluetooth proxy did not work for me, so am waiting for RS485 options eventually.

**Comment by fl4p** [comment]
v1.73 asserts soc range
