### ISSUE TITLE
Publish HA discovery mqtt data before bms sample data

### ISSUE THREAD

**Issue by scotthernandez** [fl4p/batmon-ha#163]
Unfortunately my daly bms doesn't quite work with the current code:
'''
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bmslib/models/daly.py", line 144, in _q
    raise TimeoutError(
TimeoutError: timeout awaiting result 95, got 5/6 responses

08:02:48 INFO [sampling] connecting bms DalyBt(18:81:03:03:05:EF,lifepo4-solar-1)
08:02:58 INFO [daly] normal connect failed (<class 'TimeoutError'>), connecting with scanner
'''

And because of the timeout in the last sample I suspect it is never able to publish the discovery mqtt topics that HA needs for creating the sensors.

Can you please check to see if it is easy to rearrange things to publish the discovery data before the sample data?

**Comment by fl4p** [comment]
For how many cells did you configure the BMS?

**Comment by scotthernandez** [comment]
It is a 15 cell pack - 48v system.

**Comment by scotthernandez** [comment]
It does publish data for these topics:
* meter
* switch
* mosfet_status
* soc

If that helps.

**Comment by fl4p** [comment]
I found a bug where the code wrongly computes the number of responses (the BMS sends voltages in tuples of 3)
Ill fix this with the next release.

**Comment by scotthernandez** [comment]
Great, thanks.

Does it make sense to move the discovery mqtt data check before reading/publishing the samples?

**Comment by fl4p** [comment]
Yeah kind of. The discovery function currently needs samples voltages to publish the number of cells and skip the nan fields.
I'll rewrite the code so discovery is sent out even if voltages fetch failed.

**Comment by scotthernandez** [comment]
Great, thanks.

**Comment by fl4p** [comment]
fix https://github.com/fl4p/batmon-ha/commit/dfd6e4a6da0662911097284ffec8da9910c53ed2 
is in the next release
please re-open if needed

**Comment by scotthernandez** [comment]
Thanks; will do.
