### ISSUE TITLE
MQQT diconnects on timeout if bms not answer serveral times.

### ISSUE THREAD

**Issue by Niceman35** [fl4p/batmon-ha#17]
MQQT connection is closing on my system after several hours. 
In MQQT logs where is a message "Disconnected on timeout"
This most likely happens if BMS is not sending or not updating values for some time.

**Comment by fl4p** [comment]
Hi,
can you please post the exact log (anonymised) here?

**Comment by Niceman35** [comment]
Hi. I don't have this issue now.
I changes your code locally and added mqtt_client.loop_start() after connect in main.py.
Works stable after this fix. I think you should add this too. This is the correct connect routine used in documentation.

    try:
        mqtt_client.connect(user_config.mqtt_broker, port=1883)
>>        mqtt_client.loop_start()
    except Exception as ex:
        logger.error('mqtt connection error %s', ex)

**Comment by fl4p** [comment]
Thanks, I've included this in the current release 0.0.45
