### ISSUE TITLE
Bleak support for a MicroPython port? (e.g. for ESP32)

### ISSUE THREAD

**Issue by 7wells** [fl4p/batmon-ha#179]
Hi Fabian!

Understanding that this is rather an issue tracker, sorry about my note here.

I asked at [micropython discussions](https://github.com/orgs/micropython/discussions/13215) if they knew about a way to port `bleak` from Python to MicroPython, and here's their answer:
> There's no direct support for bleak or its exact API as such. Micropython has aioble for asyncio Bluetooth: https://github.com/micropython/micropython-lib/tree/master/micropython/bluetooth/aioble

For the higher-level bluetooth `aioble library`, please refer to this:
https://github.com/micropython/micropython-lib/tree/master/micropython/bluetooth/aioble

As I am no programmer and know little of Python/MicroPython, my question there and here, too, might not be helpful. In that case, I kindly ask you to accept my apologies. 😊

If, however, you see a way that the provided information might be helpful, please let me know. Thank you so much. ❤️

I tag @snipah here as they might be interested in this, too.

**Comment by fl4p** [comment]
please discuss at the old issue
