### ISSUE TITLE
Balance Switch not available in JK BMS

### ISSUE THREAD

**Issue by arzaman** [fl4p/batmon-ha#181]
I have compelted the integration via BT with my JKBMS and I'm not able to get status of the "balance" switch
just charge/discharge swtich are visible

![image](https://github.com/fl4p/batmon-ha/assets/6697518/71e78cae-93dc-4f6d-9e61-34e9aeff55f5)

bms type and version
![image](https://github.com/fl4p/batmon-ha/assets/6697518/3cf0cd3a-11c1-45f3-910a-935da6e56090)

batmon 1.75 on RPI 3 model B 

![image](https://github.com/fl4p/batmon-ha/assets/6697518/5e2cf059-671f-401c-a6ce-40303bbd4c66)

let me know if it's possible to add
thanks
Davide

**Comment by fl4p** [comment]
Hi, I didn't implement it, for sure it's possible

**Comment by arzaman** [comment]
Ok I understood 
could be useful, not essential but in case you can add in the next release is appreciated
thanks
Davide

**Comment by dougle03** [comment]
> Ok I understood could be useful, not essential but in case you can add in the next release is appreciated thanks Davide

Hey, sorry to bother you, but do you have a copy of the yaml for the JK-BMS project that UKSA007 has now taken down? I saw in your comment to him and that he's now taken the code down to sell it privately..? Sorry to contact you on this post but I can't find another way to contact you. Thanks

**Comment by fl4p** [comment]
added balance switch reading in https://github.com/fl4p/batmon-ha/commit/22dcf47960838b0cbf5b43b1e879198e9015048a

setting the balance switch was already there.

will push this with the next update

**Comment by fl4p** [comment]
added with release 1.76

re-open if neede
