### ISSUE TITLE
Adding more Informations to JKBMS readout

### ISSUE THREAD

**Issue by sebmueller** [fl4p/batmon-ha#19]
Hi,

I use the BatMon Addon in HA since 2 weeks! Great addon!!!

Before, I used the MPP-Solar Script, runing in Background. With this, I got some more Informations from the JKBMS (JK-B2A24S20P)
I got the Average Cell Voltage, the cell difference voltage, the cell resistance, the mbs Uptime, ...
So, maybe you can add these informations also the the Batmon addon?

Kind regards
Sebastian

**Comment by kababoom** [comment]
The average voltage and voltage delta you can easily make with helper.

**Comment by fl4p** [comment]
Cell avg, min, max etc has been added.
Also JK uptime, which doesn't seem to work properly yet. Please open a new issue
