### ISSUE TITLE
Victron SmartShunt (total_energy_charge / total_energy_discharge) accuracy

### ISSUE THREAD

**Issue by RoySalisbury** [fl4p/batmon-ha#191]
I'm using the Victron SmartShunt using BLE.  The 'total_energy_charge' and 'total_energy_discharge' are bing reported, but the accuracy is at the kW level (whole number).  

Can the accuracy be configured to report the data to include the fractional data (3957.24) instead of just rounded to the whole kW (3957).  Or is this a limitation of the Victron Shunt?  

Might just need 'suggested_display_precision' added to the MQTT data.  But not sure what Victron is reporting.

**Comment by fl4p** [comment]
Hi,
I fixed this with the change referenced above and it will be in the next release

**Comment by fl4p** [comment]
fixed with release 1.77
