### ISSUE TITLE
Service won't start

### ISSUE THREAD

**Issue by AntoineLaporte** [fl4p/batmon-ha#2]
Since the latest update of HA the service is starting but no log, no cpu usage, no memory usage, and no access to the entities.
Are you experiencing the same ?

**Comment by fl4p** [comment]
I haven't upgraded to latest HA, and currently no access to my setup. I'll let you know when as soon as I can

**Comment by tokibi81** [comment]
I have an error: s6-overlay-suexec: fatal: can only run as pid 1
Batmon doesns´t start. Pleas fix it. Thanks a lot.

**Comment by fl4p** [comment]
I just pushed version 0.0.23, this should fix it.
The isssue was related to the new S6-overlay https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/
