### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by JeffyBeepBoop** [fl4p/batmon-ha#20]
"The command '/bin/ash -o pipefail -c apk add --no-cache python3 bluez py-pip git' returned a non-zero code: 4"

Any clues on how to get this to work? Rpi4, Twister OS, HA Supervised

(Also, thanks for making this, super handy!)

**Comment by fl4p** [comment]
Never heard of exit code 4. Maybe a permission / disk space error? 

To track this down, please edit `Dockerfile` and replace the lines
```
RUN \
  apk add --no-cache \
    python3 bluez py-pip git
```

with 
```
RUN apk add --no-cache python3
RUN apk add --no-cache py-pip 
RUN apk add --no-cache bluez 
RUN apk add --no-cache git

```

**Comment by JeffyBeepBoop** [comment]
Sorry, I'm kinda new to how add-ons work. How would I edit that file within the flow of using the Add-on/repo? When I add the repo, does it download it somewhere? I can also install a separate Docker container. 

Just checked again and still getting the same error after clicking install. Could it be something to do with 32bit Raspberry PiOS?

**Comment by JeffyBeepBoop** [comment]
Made a fork of the repo to test the changes you suggested. Same error. 

My disk, according to HA is only 40% full, so should have space. 

![image](https://user-images.githubusercontent.com/79879140/200081750-2897a1a5-0d4c-476f-bc6c-cea408f1c022.png)

**Comment by DryZus** [comment]
I have the same issue.

**Comment by fl4p** [comment]
Please try version 0.0.50, which doesn't fix the error but gives more insights on what package actually causes the error

**Comment by fl4p** [comment]
Closed due to inactivity. Please create a new issue if still present
