### ISSUE TITLE
Unknown BMS BM100 values ​​going up and down in one volt increments

### ISSUE THREAD

**Issue by Ordiproxi** [fl4p/batmon-ha#248]
Good morning,

The values ​​spend their time going up and down for example they go from 11.50v to 12.50 volt in increments of 1 volt once they reach 12.50 they go back down I used dummy because the other bms do not work the battery controller is a BM100 for car and 12.00 volt battery.
Bravo for your work and thank you
Describe the issue here.
If you experience bluetooth connection problems, follow these steps before opening an issue:
https://github.com/fl4p/batmon-ha#troubleshooting

* Include exact BMS model name
* Query HW and SW numbers from the BMS app
* Enable verbose_log

```
Paste log output between BEGIN and END:
BEGIN 
07:29:23 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=51302)
07:34:24 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=51602)
07:34:24 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=51602)
07:34:24 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=51602)
07:34:24 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=51602)
07:39:25 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=51902)
07:39:25 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=51902)
07:39:25 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=51902)
07:39:25 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=51902)
07:44:26 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=52202)
07:44:26 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=52202)
07:44:26 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=52202)
07:44:26 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=52202)
07:49:26 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=52502)
07:49:26 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=52502)
07:49:26 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=52502)
07:49:26 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=52502)
07:54:27 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=52802)
07:54:27 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=52802)
07:54:27 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=52802)
07:54:27 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=52802)
07:59:28 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=53102)
07:59:28 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=53102)
07:59:28 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=53102)
07:59:28 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=53102)
08:04:29 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=53402)
08:04:29 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=53402)
08:04:29 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=53402)
08:04:29 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=53402)
08:09:30 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=53702)
08:09:30 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=53702)
08:09:30 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=53702)
08:09:30 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=53702)
08:14:30 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=54002)
08:14:30 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=54002)
08:14:30 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=54002)
08:14:30 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=54002)
08:19:31 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=54302)
08:19:31 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=54302)
08:19:31 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=54302)
08:19:31 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=54302)
08:24:32 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=54602)
08:24:32 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=54602)
08:24:32 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=54602)
08:24:32 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=54602)
08:29:33 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=54902)
08:29:33 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=54902)
08:29:33 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=54902)
08:29:33 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=54902)
08:34:33 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=55202)
08:34:33 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=55202)
08:34:33 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=55202)
08:34:34 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=55202)
08:39:34 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=55502)
08:39:34 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=55502)
08:39:34 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=55502)
08:39:34 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=55502)
08:44:35 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=55802)
08:44:35 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=55802)
08:44:35 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=55802)
08:44:35 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=55802)
08:49:36 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=56102)
08:49:36 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=56102)
08:49:36 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=56102)
08:49:36 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=56102)
08:54:37 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=56402)
08:54:37 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=56402)
08:54:37 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=56402)
08:54:37 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=56402)
08:59:37 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=56702)
08:59:37 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=56702)
08:59:37 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=56702)
08:59:37 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=56702)
09:04:38 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=57002)
09:04:38 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=57002)
09:04:38 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=57002)
09:04:38 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=57002)
09:09:39 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=57302)
09:09:39 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=57302)
09:09:39 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=57302)
09:09:39 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=57302)
09:14:40 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=57602)
09:14:40 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=57602)
09:14:40 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=57602)
09:14:40 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=57602)
09:19:40 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=57902)
09:19:40 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=57902)
09:19:40 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=57902)
09:19:40 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=57902)
09:24:41 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=58202)
09:24:41 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=58202)
09:24:41 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=58202)
09:24:41 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=58202)
09:29:42 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=58502)
09:29:42 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=58502)
09:29:42 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=58502)
09:29:42 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=58502)
09:34:43 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=58802)
09:34:43 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=58802)
09:34:43 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=58802)
09:34:43 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=58802)
END
```
13:30:40 INFO [install_bleak] bleak 0.13.1a1 installed, want 0.20.2, running pip3 install bleak==0.20.2
13:30:40 INFO [install_bleak] influxdb installed=False need=False
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting bleak==0.20.2
  Downloading https://wheels.home-assistant.io/musllinux-index/bleak-0.20.2-py3-none-any.whl (135 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 4.8 MB/s eta 0:00:00
Collecting dbus-fast<2.0.0,>=1.83.0 (from bleak==0.20.2)
  Downloading dbus_fast-1.95.2-cp312-cp312-musllinux_1_1_x86_64.whl.metadata (10 kB)
Downloading dbus_fast-1.95.2-cp312-cp312-musllinux_1_1_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 33.1 MB/s eta 0:00:00
Installing collected packages: dbus-fast, bleak
  Attempting uninstall: bleak
    Found existing installation: bleak 0.13.1a1
    Uninstalling bleak-0.13.1a1:
      Successfully uninstalled bleak-0.13.1a1
Successfully installed bleak-0.20.2 dbus-fast-1.95.2
13:30:44 INFO [main] Power cycle bluetooth hardware
Unable to open mgmt_socket
Unable to open mgmt_socket
13:30:47 INFO [bt] BT Discovery:
13:30:52 INFO [bt]  - no devices found - 
13:30:52 INFO [main] Bleak version 0.20.2, BtBackend version bluez-v5.76
13:30:53 INFO [main] connecting mqtt addons@core-mosquitto
/app/main.py:196: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
  mqtt_client = paho.Client(paho.CallbackAPIVersion.VERSION1)
13:30:53 INFO [main] Fetching 4 BMS + 0 virtual + 0 others concurrently, period=1.00s, keep_alive=True
13:30:53 INFO [sampling] connecting bms DummyBt(00:00:00:37:81:BC,Batterie 1)
13:30:53 INFO [sampling] connected bms DummyBt(00:00:00:37:81:BC,Batterie 1)!
13:30:53 INFO [sampling] Batterie 1 subscribing for {'charge': True, 'discharge': True} switch change
13:30:53 INFO [sampling] Batterie 1: BmsSampl(96.6%,U=11.5V,I=-0.90A,P=-10W,Q=97/100Ah,mos=nan°C)
13:30:53 INFO [sampling] Batterie 1 volt=[2996,3006,3016,3026] temp=[nan]
13:30:53 INFO [sampling] Sending HA discovery for Batterie 1 (num_samples=0)
13:30:53 INFO [sampling] connecting bms DummyBt(00:00:00:0F:F7:89,Batterie 4)
13:30:53 INFO [sampling] connected bms DummyBt(00:00:00:0F:F7:89,Batterie 4)!
13:30:53 INFO [sampling] Batterie 4 subscribing for {'charge': True, 'discharge': True} switch change
13:30:53 INFO [sampling] Batterie 4: BmsSampl(28.6%,U=12.5V,I=0.95A,P=12W,Q=29/100Ah,mos=nan°C)
13:30:53 INFO [sampling] Batterie 4 volt=[3004,3014,3024,3034] temp=[nan]
13:30:53 INFO [sampling] Sending HA discovery for Batterie 4 (num_samples=0)
13:30:53 INFO [sampling] connecting bms DummyBt(00:00:00:38:98:DB,Batterie 3)
13:30:53 INFO [sampling] connected bms DummyBt(00:00:00:38:98:DB,Batterie 3)!
13:30:53 INFO [sampling] Batterie 3 subscribing for {'charge': True, 'discharge': True} switch change
13:30:53 INFO [sampling] Batterie 3: BmsSampl(95.4%,U=11.5V,I=-0.93A,P=-11W,Q=95/100Ah,mos=nan°C)
13:30:53 INFO [sampling] Batterie 3 volt=[2996,3006,3016,3026] temp=[nan]
13:30:53 INFO [sampling] Sending HA discovery for Batterie 3 (num_samples=0)
13:30:53 INFO [sampling] connecting bms DummyBt(00:00:00:D9:79:B7,Batterie 2)
13:30:53 INFO [sampling] connected bms DummyBt(00:00:00:D9:79:B7,Batterie 2)!
13:30:53 INFO [sampling] Batterie 2 subscribing for {'charge': True, 'discharge': True} switch change
13:30:53 INFO [sampling] Batterie 2: BmsSampl(23.8%,U=12.5V,I=0.98A,P=12W,Q=24/100Ah,mos=nan°C)
13:30:53 INFO [sampling] Batterie 2 volt=[3004,3014,3024,3034] temp=[nan]
13:30:53 INFO [sampling] Sending HA discovery for Batterie 2 (num_samples=0)
13:30:53 INFO [main] mqtt watchdog loop started with timeout 300.0s

**Comment by fl4p** [comment]
the  `dummy` bms is intented for integration testing only, there is no real connection to a physical BMS, it just produces random data.

**Comment by Ordiproxi** [comment]
Thank you for your answer for "dummy" I understood it after it was a virtual bms example.
I try this one:
Vgate BA100 Car Battery Tester Monitor 12V Bluetooth 4.0 Battery Assistant Works with iOS and Android Phones with 2023

https://fr.aliexpress.com/item/1005005227272827.html?spm=a2g0o.order_list.order_list_main.21.28ae5e5bj4Q2OF&gatewayAdapt=glo2fra

**Comment by fragolinux** [comment]
> Thank you for your answer for "dummy" I understood it after it was a virtual bms example. I try this one: Vgate BA100 Car Battery Tester Monitor 12V Bluetooth 4.0 Battery Assistant Works with iOS and Android Phones with 2023
> 
> https://fr.aliexpress.com/item/1005005227272827.html?spm=a2g0o.order_list.order_list_main.21.28ae5e5bj4Q2OF&gatewayAdapt=glo2fra

hi @fl4p i've this same device, vgate ba100: https://www.aliexpress.com/item/1005006485246319.html
tried each protocol with no luck... is it supported? Phone app works just fine, device too
TIA

**Comment by Ordiproxi** [comment]
hi @fl4p i've this same device, vgate ba100: https://www.aliexpress.com/item/1005006485246319.html
tried each protocol with no luck... is it supported? Phone app works just fine, device too
TIA

Hello, no it does not work with batmoon
Good day

**Comment by fragolinux** [comment]
any chance it will be added in the future? any help i can give extracting whatever data, if you guide me? thanks

**Comment by fl4p** [comment]
> hi [@fl4p](https://github.com/fl4p) i've this same device, vgate ba100: https://www.aliexpress.com/item/1005006485246319.html tried each protocol with no luck... is it supported? Phone app works just fine, device too TIA
> 
> Hello, no it does not work with batmoon Good day

Hi, if you are still interested, please open a new issue
