### ISSUE TITLE
Implement JK04 for JK-bms

### ISSUE THREAD

**Issue by fl4p-old** [fl4p/batmon-ha#3]
* Infer protocol version from bms version?
* Implement JK04

**Comment by fl4p** [comment]
JK04 appears to be the older protocol
https://github.com/syssi/esphome-jk-bms/blob/aa059f6089afb3c2c8a5b7c248059581cfc7ebaa/esp32-ble-example.yaml

**Comment by fl4p** [comment]
Currently tested & workig:

- [x] JK-B2A24S20P

**Comment by Catchmydrift** [comment]
> Currently tested & workig:
> 
> * [x]  JK-B2A24S20P

hi, do you mean this batmon works with the jk-b2a24s20p?   as i have 2 of them and cant get either to connect..
