### ISSUE TITLE
Add-on not available?

### ISSUE THREAD

**Issue by UV-PWRD** [fl4p/batmon-ha#30]
I've added the repository, but there's no batmon in my list of available add-ons?

![image](https://user-images.githubusercontent.com/92243144/199154392-881d4a77-f361-4ec3-a7dc-249dc58c4176.png)

**Comment by prezes210** [comment]
@UV-PWRD try to restart HomeAssistance `Settings->System->RESTART` (in upper right corner)

**Comment by UV-PWRD** [comment]
> @UV-PWRD try to restart HomeAssistance `Settings->System->RESTART` (in upper right corner)

Embarrassed to say I hadn't done this and of course it resolved it... 

*facepalm*
