### ISSUE TITLE
not a real issue, but somebody might have a solution.

### ISSUE THREAD

**Issue by blablaaddi** [fl4p/batmon-ha#37]
Hi, I'm running a 16S setup with a JBD BMS which is just communicating via BT. Batmon log is showing that it gets all required valous from the BMS.
INFO     [sampling.py:100] JbdBt(A4:C1:37:00:03:C9) times: connect=0.00s fetch=0.16s
INFO     [sampling.py:68] BMS1 result@2022-11-24T13:34:09.862145 BmsSample(U=51.0V,I=-2.10A,P=-107W,q=44.8Ah/280.0,mos=nan°C)
INFO     [sampling.py:75] BMS1 volt=3187,3184,3185,3187,3186,3186,3186,3186,3188,3187,3186,3187,3186,3188,3185,3183 temp=[7.1, 13.8, 12.3]

but the graph in HA differs between cells 1-8 and 9-16, as 9-16 writes 0 values occasionally.

changed now the sampling period from 1 to 5 seconds.

**Comment by fl4p** [comment]
do the 0 values ever appear in the logs?
