### ISSUE TITLE
Standalone JBD hangs on connect no response and no timeout

### ISSUE THREAD

**Issue by flambert860** [fl4p/batmon-ha#48]
For some reason it seems like that the:
`await self.client.connect(timeout=timeout)`
hangs the process, if I ctrl-c it says connected after some time, and also it does not timeout after 20 sec or longer.

It's very weird because I had my own python code which talks with the bms also using Bleak, but found your implemtation more done and looked really mature.

Anyone who might have a clue how to prevent the connect to hang?

**Comment by flambert860** [comment]
Seems to be a problem with the threading, when connecting in the main before starting the other threads, but then it get stucks when trying to write the GATTs

**Comment by flambert860** [comment]
More findings, as suspected the 
`asyncio.create_task(background_loop(timeout=max(120., sample_period * 3) if watchdog_en else 0))`
Causes my issues, so when commenting it out it works, anyhow I can fix this?

**Comment by fl4p** [comment]
this should've been fixed some time ago. please re-open if not
