### ISSUE TITLE
JBD/xiaoxiang BMS triggers math.isfinite(soc) assertion due to incorrectly parsed unsigned capacity

### ISSUE THREAD

**Issue by owpole** [fl4p/batmon-ha#60]
Debug data from my BMS:
0a:3f 26.23V
00:6f 1.11A
71:7d 290.53 AH charge
da:c0 560.00 AH capacity -- this should be parsed as unsigned, otherwise it's negative.
remaining bytes: 00:00:2c:f3:00:00:00:00:00:00:16:34:03:08:02:0b:64:0b:5f:fa:56:77

I think that the only signed field here should be current:
https://github.com/fl4p/batmon-ha/blob/master/bmslib/jbd.py#L84-L90
I haven't confirmed that, but the data from at least my device is correct in home assistant with that change.

**Comment by fl4p** [comment]
You're probably right.
Can you send me a sample of your BMS response frame?

**Comment by fl4p** [comment]
Thanks, 0.0.52 fixes this
