### ISSUE TITLE
mqtt connection error

### ISSUE THREAD

**Issue by jirdol** [fl4p/batmon-ha#61]
Hello,

I have a connection problem. BT finds the device but always writes ERROR.
can you advise please?

Thank you very much.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
INFO     [main.py:68] BT Discovery:
INFO     [main.py:73] BT Device   JK-B2A24S20P   address=C8:47:8C:EA:68:38
INFO     [bt.py:133] BMS JKBt(CC:44:88:FF:AA:BB) keep alive enabled
INFO     [main.py:195] connecting mqtt @core-mosquitto
ERROR    [main.py:208] mqtt connection error [Errno -2] Name does not resolve
INFO     [main.py:232] Fetching 1 BMS + 0 others serially, period=1.00s, keep_alive=True
INFO     [sampling.py:61] connecting bms JKBt(CC:44:88:FF:AA:BB)
INFO     [main.py:106] mqtt watchdog loop started with timeout 120.0s

**Comment by zingreen** [comment]
Looks like you have no installed mqtt addon.
