### ISSUE TITLE
Works perfectly with my JK BMS for a few days, then crashes when parsing some json response

### ISSUE THREAD

**Issue by georgepauna** [fl4p/batmon-ha#69]
First of all, thanks a lot for this amazing addon.

As mentioned all good for few days, then needs restart

Here is log:

06:43:58 INFO [sampling] battery1 volt=3708,3709,3709,3709,3711,3709,3707,3709,3709,3709,3709,3709,3708,3709 temp=[20.0, 19.7]
06:44:09 INFO [sampling] battery1: BmsSample(U=51.9V,I=-0.22A,P=-11W,q=105.5Ah/200.0,mos=21.6°C)
06:44:09 INFO [sampling] battery1 volt=3708,3709,3709,3709,3712,3711,3707,3711,3709,3709,3709,3709,3709,3711 temp=[20.0, 19.7]
06:44:20 INFO [sampling] battery1: BmsSample(U=51.9V,I=-0.22A,P=-11W,q=105.5Ah/200.0,mos=21.6°C)
06:44:20 INFO [sampling] battery1 volt=3708,3709,3709,3711,3712,3709,3707,3709,3711,3709,3709,3709,3709,3709 temp=[20.0, 19.7]
06:44:28 WARNING [bt] BMS JKBt(C8:47:8C:F7:C2:8B) disconnected!
06:44:28 INFO [sampling] {3: bytearray(b'U\xaa\xeb\x90\x03\x1dJK-B1A24S15P\x00\x00\x00\x0010.X-W\x00\x0010.02\x00\x00\x00\x98\x91\xa7\x01\x0b\x00\x00\x00ID4-4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001234\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00220113\x00\x001120301092\x000000\x00Input Userdata\x00\x00123456\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1d\xaaU\x90\xeb\xc8\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00D'), 1: bytearray(b'U\xaa\xeb\x90\x01\x1dX\x02\x00\x00\xe4\x0c\x00\x00\x16\r\x00\x006\x10\x00\x00\x04\x10\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb8\x0b\x00\x00\xf0I\x02\x00\x1e\x00\x00\x00<\x00\x00\x00\xf0I\x02\x00,\x01\x00\x00<\x00\x00\x00<\x00\x00\x00\xe8\x03\x00\x00\xbc\x02\x00\x00X\x02\x00\x00\xbc\x02\x00\x00X\x02\x00\x008\xff\xff\xff\x9c\xff\xff\xff\x84\x03\x00\x00\xbc\x02\x00\x00\x0e\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00@\r\x03\x00\xdc\x05\x00\x00\xb8\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xd4\xaaU\x90\xeb\xc8\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00D'), 2: bytearray(b"U\xaa\xeb\x90\x02\x98|\x0e}\x0e}\x0e\x7f\x0e\x80\x0e\x7f\x0e{\x0e\x7f\x0e\x7f\x0e}\x0e}\x0e}\x0e|\x0e}\x0e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff?\x00\x00~\x0e\x05\x00\x04\x06T\x01@\x01=\x01K\x01T\x01\x07\x01\xf7\x007\x018\x012\x017\x014\x012\x01\xf3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xde\xca\x00\x009,\x00\x00&\xff\xff\xff\xc8\x00\xc5\x00\xd8\x00\x00\x00\x00\x00\x004\xfe\x9b\x01\x00@\r\x03\x00\x16\x00\x00\x00w\'D\x00d\x00v\x05\xd7\x91\xa7\x01\x01\x01\xa6\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x00\x01\x00\x00\x00F\x04\x00\x00\x01\x00\xa1u>@\x00\x00\x00\x00\xe2\x04\xd40\x00\x00\x00\x01\x00\x05\x00\x00\x02\xffP\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xab")} bms debug data: battery1
Traceback (most recent call last):
  File "/app/main.py", line 270, in main
    await fetch_loop(fn, period=sample_period, max_errors=max_errors)
  File "/app/main.py", line 83, in fetch_loop
    await fn()
  File "/app/main.py", line 263, in fn
    await t
  File "/app/bmslib/sampling.py", line 50, in __call__
    return await self.sample()
  File "/app/bmslib/sampling.py", line 72, in sample
    sample = await bms.fetch()
  File "/app/bmslib/jikong.py", line 165, in fetch
    await self._fetch_futures.wait_for(0x02, self.TIMEOUT)
  File "/app/bmslib/__init__.py", line 46, in wait_for
    return await asyncio.wait_for(self._futures.get(name), timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 299, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
06:44:28 INFO [main] exit signal handler... (), {}, shutdown already False
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by fl4p** [comment]
The watchdog will restart the add-on. Did you enable it?

**Comment by georgepauna** [comment]
For some reason watchdog doesn't restart it. Right now it is stopped for 7h30 min.
I think it's because watchdog doesn't see it as a crash, but as a controlled stop (log shows the same, addon reports a stop)

**Comment by fl4p** [comment]
I've noticed similar behavior.
I'll add a try-except , so the last sys.exit(1) is always reached
```
try:
    asyncio.run(main())
except Exception as e:
    logger.error("Main loop exception: %s", e)
    logger.error('Stack: %s', traceback.format_exc())
sys.exit(1)
```

I just pushed this change

**Comment by georgepauna** [comment]
Nice, but I don't see it as an update in HA.

**Comment by georgepauna** [comment]
Thanks for looking into it. Update came in HA and now watchdog usually restarts it.
For some reason it seems it's now happening very often, almost every minute, so a better fix would be to actually handle the above case.
Also, there is still this case when it's not crashing, but stopping, so watchdog doesn't restart the addon (I see very similar call stack) - this happened 10 hours ago, addon remained stopped:

> 23:21:51 INFO [sampling] battery1: BmsSample(U=50.3V,I=-7.88A,P=-396W,q=57.3Ah/200.0,mos=21.3°C)
23:21:51 INFO [sampling] battery1 volt=3596,3596,3596,3593,3593,3591,3586,3592,3595,3595,3595,3593,3591,3590 temp=[19.3, 18.8]
23:21:55 INFO [sampling] battery1: BmsSample(U=50.3V,I=-8.10A,P=-407W,q=57.3Ah/200.0,mos=21.3°C)
23:21:55 INFO [sampling] battery1 volt=3593,3595,3596,3593,3595,3596,3591,3595,3592,3591,3591,3591,3592,3591 temp=[19.3, 18.8]
23:21:59 INFO [sampling] battery1: BmsSample(U=50.3V,I=-8.10A,P=-407W,q=57.2Ah/200.0,mos=21.3°C)
23:21:59 INFO [sampling] battery1 volt=3593,3592,3592,3591,3593,3596,3591,3595,3592,3593,3595,3593,3593,3590 temp=[19.3, 18.8]
23:22:04 INFO [sampling] battery1: BmsSample(U=50.3V,I=-8.31A,P=-418W,q=57.2Ah/200.0,mos=21.3°C)
23:22:04 INFO [sampling] battery1 volt=3596,3595,3591,3592,3596,3595,3591,3595,3592,3591,3591,3590,3592,3591 temp=[19.3, 18.8]
23:22:09 INFO [sampling] battery1: BmsSample(U=50.3V,I=-7.88A,P=-396W,q=57.2Ah/200.0,mos=21.3°C)
23:22:09 INFO [sampling] battery1 volt=3591,3591,3596,3595,3593,3592,3586,3591,3593,3595,3593,3593,3592,3590 temp=[19.3, 18.8]
23:22:18 WARNING [bt] BMS JKBt(C8:47:8C:F7:C2:8B) disconnected!
23:22:18 INFO [sampling] {3: bytearray(b'U\xaa\xeb\x90\x03\x9bJK-B1A24S15P\x00\x00\x00\x0010.X-W\x00\x0010.02\x00\x00\x00p\xc6\xa9\x01\x0b\x00\x00\x00ID4-4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001234\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00220113\x00\x001120301092\x000000\x00Input Userdata\x00\x00123456\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xaa\xaaU\x90\xeb\xc8\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00D'), 1: bytearray(b'U\xaa\xeb\x90\x01\x9bX\x02\x00\x00\xe4\x0c\x00\x00\x16\r\x00\x006\x10\x00\x00\x04\x10\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb8\x0b\x00\x00\xf0I\x02\x00\x1e\x00\x00\x00<\x00\x00\x00\xf0I\x02\x00,\x01\x00\x00<\x00\x00\x00<\x00\x00\x00\xe8\x03\x00\x00\xbc\x02\x00\x00X\x02\x00\x00\xbc\x02\x00\x00X\x02\x00\x008\xff\xff\xff\x9c\xff\xff\xff\x84\x03\x00\x00\xbc\x02\x00\x00\x0e\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00@\r\x03\x00\xdc\x05\x00\x00\xb8\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00R\xaaU\x90\xeb\xc8\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00D'), 2: bytearray(b'U\xaa\xeb\x90\x02\x0b\x07\x0e\x07\x0e\x08\x0e\x0c\x0e\x0c\x0e\t\x0e\x02\x0e\x07\x0e\x07\x0e\x08\x0e\x0b\x0e\x0b\x0e\x0b\x0e\x07\x0e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff?\x00\x00\x08\x0e\n\x00\x02\x06T\x01@\x01=\x01K\x01T\x01\x07\x01\xf7\x007\x018\x012\x017\x014\x012\x01\xf3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00o\xc4\x00\x00\x1f\x0b\x06\x00<\xe1\xff\xff\xc1\x00\xbc\x00\xd5\x00\x00\x00\xe2\xfd\x02\x1c\x86\xdf\x00\x00@\r\x03\x00\x16\x00\x00\x00\xcc\xdcE\x00d\x00\x98\x054\xc7\xa9\x01\x01\x01\xa7\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x00\x01\x00\x00\x00F\x04\x00\x00$\x00\xa1u>@\xe4\x00\x00\x00\xe2\x04\xd40\x00\x00\x00\x01\x00\x05\x00\x00\xa0\x14g\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa8')} bms debug data: battery1
Traceback (most recent call last):
  File "/app/main.py", line 276, in main
    await fetch_loop(fn, period=sample_period, max_errors=max_errors)
  File "/app/main.py", line 84, in fetch_loop
    await fn()
  File "/app/main.py", line 269, in fn
    await t
  File "/app/bmslib/sampling.py", line 50, in __call__
    return await self.sample()
  File "/app/bmslib/sampling.py", line 72, in sample
    sample = await bms.fetch()
  File "/app/bmslib/jikong.py", line 165, in fetch
    await self._fetch_futures.wait_for(0x02, self.TIMEOUT)
  File "/app/bmslib/__init__.py", line 46, in wait_for
    return await asyncio.wait_for(self._futures.get(name), timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 306, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
23:22:18 INFO [main] exit signal handler... (), {}, shutdown already False
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by fl4p** [comment]
It crashes intentionally to reset anything that's stalled. BLE stack can be buggy. If you want 100% reliability use a wired connection to your BMS

**Comment by georgepauna** [comment]
You mean the logs above show intentional crashes? It looks to me like BMS giving some info, I see the BMS model, name, uptime and fw version in that garbled data, which is crashing the batmon parser.

**Comment by fl4p** [comment]
It doesn't crash during parsing and there is no JSON.
Batmon exits when it believes it makes sense (or there is some other bug). It can run for months with a stable BT connection.
