### ISSUE TITLE
cannot import name 'load_user_config' from partially initialized module

### ISSUE THREAD

**Issue by mfcakir** [fl4p/batmon-ha#70]
After update i can't start the module 
Traceback (most recent call last):
  File "/app/main.py", line 22, in <module>
    from bmslib.store import load_user_config
  File "/app/bmslib/store.py", line 7, in <module>
    from main import logger
  File "/app/main.py", line 22, in <module>
    from bmslib.store import load_user_config
ImportError: cannot import name 'load_user_config' from partially initialized module 'bmslib.store' (most likely due to a circular import) (/app/bmslib/store.py)

![batmon](https://user-images.githubusercontent.com/12495812/228757010-ee75ae76-50f2-4177-8545-05e099f9fca1.PNG)

**Comment by bjoernh** [comment]
same here, `git checkout v0.0.54` and rebuilding the container image fix it. But something is broken on the main branch :)

**Comment by fl4p** [comment]
Fixed https://github.com/fl4p/batmon-ha/commit/1e3d5117558bc66d6b989e5a73053434e64443da
