### ISSUE TITLE
'alias' seems to be mandatory, not optional

### ISSUE THREAD

**Issue by 7wells** [fl4p/batmon-ha#73]
Hi @fl4p!

Thanks a lot for this great tool! 😄

I have a question/issue, i.e. the README says:
> With the `alias` field you can set the name as displayed in Home Assistant. Otherwise, the name as found in Bluetooth discovery is used.

So I thought that `alias` is optional, but it seems that it is not. When I omit it from the config, I get this error in the log:
`AttributeError: 'NoneType' object has no attribute 'name'`

Could you please confirm whether it is mandatory or optional and maybe make it a bit clearer in the README? Thank you so much for your time. 👍

**Comment by fl4p** [comment]
Alias is optional. However, if batmon can't resolve the name through BT discovery it raises the error you found.
