### ISSUE TITLE
Missing file: /data/bms_meter_states.json

### ISSUE THREAD

**Issue by ornolio** [fl4p/batmon-ha#76]
I got the following warning:
11:44:21 WARNING [main] Failed to load meter states: [Errno 2] No such file or directory: '/data/bms_meter_states.json'
My 4 x BMS are all jbd. 
How can I fix it?
Thank you

**Comment by fl4p** [comment]
You can ignore this, only happens on first run. I will remove this warning with the next update

**Comment by ornolio** [comment]
Thank You very much.
Best Regards.
p.

pier giacomo ornolio
***@***.***
***@***.***
pec: ***@***.***
+39 335 78 31 433
In data 7 aprile 2023 14:37:58 Fabian ***@***.***> ha scritto:
