### ISSUE TITLE
MQTT Issue

### ISSUE THREAD

**Issue by Zippa1204** [fl4p/batmon-ha#81]
Running Batmon as standalone, but I get the following when starting it:

17:50:59 INFO [bt] BMS JKBt(C8:47:8C:E8:DD:F1) keep alive enabled
17:50:59 INFO [bt] BMS JKBt(C8:47:8C:E9:2E:DD) keep alive enabled
17:50:59 INFO [main] connecting mqtt MQTT@20.0.0.40
17:50:59 ERROR [main] mqtt connection error 'Client' object has no attribute '_on_pre_connect'

Does not seem to publish the data to my HA MQTT instance....

17:51:06 WARNING [mqtt_util] mqtt publish JK-Slave/cell_voltages/1 failed: 4 (4, 196)
17:51:06 WARNING [mqtt_util] mqtt publish JK-Slave/cell_voltages/2 failed: 4 (4, 197)
17:51:06 WARNING [mqtt_util] mqtt publish JK-Slave/cell_voltages/3 failed: 4 (4, 198)
17:51:06 WARNING [mqtt_util] mqtt publish JK-Slave/cell_voltages/4 failed: 4 (4, 199)
17:51:06 WARNING [mqtt_util] mqtt publish JK-Slave/cell_voltages/5 failed: 4 (4, 200)
17:51:06 WARNING [mqtt_util] mqtt publish JK-Slave/cell_voltages/6 failed: 4 (4, 201)

**Comment by fl4p-old** [comment]
which paha version do you have installed?
`pip show paho`
