### ISSUE TITLE
Jk bms B2A20S20P - problem with connection

### ISSUE THREAD

**Issue by Tesla72PL** [fl4p/batmon-ha#85]
Hello, can you help mi with my bms, somethims working good but after 1-2days have problems with communication and cant connect to bms

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
14:49:30 INFO [main] BT Discovery:
14:49:35 INFO [main] BT Device   JK_B2A20S20P   address=C8:47:8C:EC:BE:E3
14:49:35 INFO [main] connecting mqtt mqttuser@core-mosquitto
14:49:35 INFO [main] Fetching 1 BMS + 0 others serially, period=20.00s, keep_alive=False
14:49:35 INFO [sampling] connecting bms JKBt(C8:47:8C:EC:BE:E3)
14:49:35 INFO [main] mqtt watchdog loop started with timeout 120.0s
14:49:47 INFO [sampling] connected bms JKBt(C8:47:8C:EC:BE:E3)!
14:49:53 ERROR [sampling] battery1 error: Not connected
14:49:53 INFO [sampling] {3: bytearray(b'U\xaa\xeb\x90\x035JK_B2A20S20P\x00\x00\x00\x0011.XW\x00\x00\x0011.26H\x00\x00\xfc\x10 \x00\x08\x00\x00\x00JK_B2A20S20P\x00\x00\x00\x001234\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00230327\x00\x003010545107\x000000\x00Input Userdata\x00\x00123\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Input Userdata\x00\x00|\xf8\xff\xff\x9f\r\x00\x00\x00\x00\x00\x00\x90\x0f\x00\x00\x00\x00\xc0\xd8\x03\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfe\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08'), 1: bytearray(b'U\xaa\xeb\x90\x015X\x02\x00\x00\x08\x0c\x00\x00N\x0c\x00\x00\xde\r\x00\x00\xac\r\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x86\x0b\x00\x00\x808\x01\x00\x1e\x00\x00\x00<\x00\x00\x00\x90_\x01\x00,\x01\x00\x00<\x00\x00\x00<\x00\x00\x00\xd0\x07\x00\x00^\x01\x00\x00,\x01\x00\x00^\x01\x00\x00,\x01\x00\x00\x1e\x00\x00\x00<\x00\x00\x00 \x03\x00\x00\xbc\x02\x00\x00\x10\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\xe0\x93\x04\x00\xdc\x05\x00\x00z\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb0q\x0b\x00\x08\x00\x00\x00\x00|\xf8\xff\xff\x9f\r\x00\x00\x00\x00\x00\x00\xcd'), 2: bytearray(b'U\xaa\xeb\x90\x025\x89\r{\r|\r\x84\r\x81\r\x82\rs\rq\rp\r\x81\re\rw\r\x84\ry\r\x87\r\x83\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\x00\x00|\r#\x00\x00\ny\x00u\x00n\x00r\x00e\x00`\x00t\x00o\x00j\x00l\x00^\x00V\x00X\x00d\x00{\x00o\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x00\x00\x00\x00\x00\xbe\xd7\x00\x00\xe2\x15\x1c\x00.\x82\x00\x00\x94\x00\x9a\x00\x00\x00\x00\x00\xe5\x07\x01_\xd6c\x04\x00\xe0\x93\x04\x00\x06\x00\x00\x00\xd8\xe6\x1b\x00d\x00\x00\x00\x0f\x12 \x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x01\x00\x00\x00\x18\x04\x9f\x00\x00\x00"d>@\x00\x00\xaa\x01\x93\x15\x00\x00\x00\x01\x00\x01\x00\x05\x00\x00\xb7\xc7\x11\x00\x00\x00\x00\x00\xac\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfe\xff\x7f\xdc/\x01\x01\x01\x00\x00\x00\x000')} bms debug data: battery1
14:49:53 ERROR [main] 1 exceptions occurred fetching BMSs
14:49:53 ERROR [main] Error (num 1, max 200) reading BMS: Not connected
14:49:53 ERROR [main] Stack: Traceback (most recent call last):
  File "/app/bmslib/sampling.py", line 74, in sample
    sample = await bms.fetch()
  File "/app/bmslib/jikong.py", line 207, in fetch
    await self._fetch_futures.wait_for(0x02, self.TIMEOUT)
  File "/app/bmslib/__init__.py", line 46, in wait_for
    return await asyncio.wait_for(self._futures.get(name), timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 45, in fetch_loop
    await fn()
  File "/app/main.py", line 239, in fn
    raise exceptions[0]
  File "/app/main.py", line 234, in fn
    await t
  File "/app/bmslib/sampling.py", line 51, in __call__
    return await self.sample()
  File "/app/bmslib/sampling.py", line 70, in sample
    async with bms:
  File "/app/bmslib/bt.py", line 178, in __aexit__
    await self.disconnect()
  File "/app/bmslib/jikong.py", line 134, in disconnect
    await self.client.stop_notify(self.UUID_RX)
  File "/usr/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 1092, in stop_notify
    raise BleakError("Not connected")
bleak.exc.BleakError: Not connected`

**Comment by fl4p** [comment]
Did you try to enable `keep_alive`?

**Comment by fl4p** [comment]
Can you try this version https://github.com/fl4p/batmon-ha/releases/tag/v0.0.60-bleak-0.20.2

**Comment by fl4p** [comment]
* Remove the add-on store repository
* Download an old release from https://github.com/fl4p/batmon-ha/tags
* Extract the contents of the ZIP file into Home Assistant's `/addons/batmon-ha` folder (using FTP, Samba Share, etc.).
* The add-on will appear in the add-on store under "Local Addons" (click 'Check for updates')

**Comment by fl4p** [comment]
> why is hci1 when i setting hci0?  

this appears to be a bug, I pushed a fix here
