### ISSUE TITLE
MQTT connection Problem

### ISSUE THREAD

**Issue by schris91** [fl4p/batmon-ha#89]
i am trying stand alone version to issue a connection via mqtt to iobroker. When i type in my MQTT Server adress and port (10.0.0.46:1884) i got a connection error.

**Comment by fl4p** [comment]
Set the port with the option `mqtt_port`, and remove `:1884` from `mqtt_broker`

**Comment by schris91** [comment]
there is no "mqtt_port". pls help :o


],
  "mqtt_broker": "homeassistant.local",
  "mqtt_user": "pv",
  "mqtt_password": "Offgrid",
  "concurrent_sampling": false,
  "keep_alive": true,
  "sample_period": 1.0,
  "publish_period": 1.0,
  "invert_current": false,
  "expire_values_after": 20,
  "verbose_log": false,
  "watchdog": false
}

**Comment by fl4p** [comment]
Just add it to the json
