### ISSUE TITLE
Remote PI - HA configuraiton

### ISSUE THREAD

**Issue by RoySalisbury** [fl4p/batmon-ha#9]
Once I have the remote PI feeding in the MQTT messages, how do I setup the local HA configuration.  Its not talking to the bluetooth address, so what do you use?

**Comment by Ghostkls** [comment]
If configured correctly and messages are reaching your MQTT broker, you should see it listed as an additional device in Integrations, MQTT. From there you can add to dashboard or use as required.

**Comment by RoySalisbury** [comment]
Got it...  And I can see the messages being sent.  Thanks.
